### ISSUE TITLE
Server World generation not working

### ISSUE THREAD

**Issue by Zeithammer** [xJon/Hexxit-II#105]
**Java 8 Update 311 (Build 1.8.0_311-b11)**

When i join my Server, **there's no Modified Terrain/World** generation (it's generating the default world)

My friend had the same issue like me.

Hosting the server with our own Pc's

**Comment by xJon** [comment]
Are you launching the server using the launch server script? Also, please include the server log for further troubleshooting.

**Comment by Zeithammer** [comment]
launching the server via an selfamed .bat file. Server works fine, no errors in the console. Just the world generation is still the default generation one.
 Trying to launch the server via the launch script gives me the following errors;

[Hexxit II] Server is starting...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

**Comment by Zeithammer** [comment]
All drivers are up to date. using Win 11

**Comment by xJon** [comment]
> Hi, you need to make sure you have Java SE 8 64-bit installed on your computer :)
You can find it through [here](https://www.java.com/en/download/manual.jsp).
Also, if you don't need the Java Development Kit version you currently have installed, you should remove it to avoid conflicts.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
