### ISSUE TITLE
when starting an old server(one that has been opened before) it freezes and server wont start but using a fresh one works

### ISSUE THREAD

**Issue by GLUEHazard** [xJon/Hexxit-II#201]
**Basic details**
- **Are you using Java 8, 64-bit?**:  yes
- **Did you add any additional mods**:  no
- **Crash/latest log link (if applicable)**:https://mclo.gs/0FqeIsi

**Describe the issue**
when starting an old server (one that has been opened before) it freezes and server wont start. But, using a fresh install of a server it works

**Comment by xJon** [comment]
The log you shared seems to end abruptly, is that all of it?

**Comment by GLUEHazard** [comment]
Yes it stops there my server runs for about 5 min and then freezes

**Comment by GLUEHazard** [comment]
actually there might be a character limit

**Comment by GLUEHazard** [comment]
[debug.log](https://github.com/xJon/Hexxit-II/files/11413733/debug.log)

**Comment by GLUEHazard** [comment]
this file is the full log

**Comment by xJon** [comment]
This log shows the server starting and a player joining, are you sure it's the correct log?

**Comment by GLUEHazard** [comment]
yes. so the server would finally start and run for a maximum of 5 min then freeze. i can stay in the game for about another minute and then it says timed out

**Comment by GLUEHazard** [comment]
I have 8GB of ram alocated to the server so i dont think its an issue there

**Comment by xJon** [comment]
Can you include the part of the log in which the server freezes?

**Comment by GLUEHazard** [comment]
it just stops working like i cant connect to the server anymore and the cmd promt stays up but i cant type anything in

**Comment by GLUEHazard** [comment]
idk if its a network issue or what and how to fix it

**Comment by GLUEHazard** [comment]
it only happens with technic servers both texxit and hexit do the same thing

**Comment by xJon** [comment]
So does it happen also with newer servers?

**Comment by GLUEHazard** [comment]
No, it doesn't.

**Comment by GLUEHazard** [comment]
it only happens after the server has been started up a second time

**Comment by xJon** [comment]
@GLUEHazard Could you share a thread dump (information from the process thread that's running your server) once your server is frozen / not responding?
You'd need to have Java JDK installed (e.g. https://adoptium.net/), then run in cmd `jstack <pid>`, where `<pid>` is equal to the the process ID number of your server (you can view it in task manager under `Processes` by enabling the PID column).

**Comment by GLUEHazard** [comment]
Server wont start once I installed java jdk Sent from Mail for Windows From: JonSent: Sunday, May 7, 2023 12:45 PMTo: xJon/Hexxit-IICc: GLUEHazard; MentionSubject: Re: [xJon/Hexxit-II] when starting an old server(one that has been opened before) it freezes and server wont start but using a fresh one works (Issue ***@***.*** Could you share a thread dump (information from the process thread that's running your server) once your server is frozen / not responding?You'd need to have Java JDK installed (e.g. https://adoptium.net/), then run in cmd jstack <pid>, where <pid> is equal to the the process ID number of your server (you can view it in task manager under Processes by enabling the PID column).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ACGaming** [comment]
You have most likely installed an incompatible JDK, you need Java 8 64-bit.

**Comment by GLUEHazard** [comment]
11648: jvm.dll not loaded by target process
The -F option can be used when the target process is not responding

**Comment by GLUEHazard** [comment]
Error attaching to core file: Windbg Error: OpenDumpFile failed!
sun.jvm.hotspot.debugger.DebuggerException: Windbg Error: OpenDumpFile failed!
        at sun.jvm.hotspot.debugger.windbg.WindbgDebuggerLocal.attach0(Native Method)
        at sun.jvm.hotspot.debugger.windbg.WindbgDebuggerLocal.attach(WindbgDebuggerLocal.java:160)
        at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:673)
        at sun.jvm.hotspot.HotSpotAgent.setupDebuggerWin32(HotSpotAgent.java:569)
        at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:335)
        at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
        at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:156)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:191)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
        at sun.tools.jstack.JStack.main(JStack.java:106)

**Comment by xJon** [comment]
@GLUEHazard Is that what's printed to the console after you use `jstack <pid>`?

**Comment by GLUEHazard** [comment]
yes

**Comment by GLUEHazard** [comment]
so i did 
jstack 5880 (which is the PID for the Java process) and it just hangs

**Comment by GLUEHazard** [comment]
Microsoft Windows [Version 10.0.22000.1880]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>jstack 5880

**Comment by xJon** [comment]
So it hangs rather than print the other things?

**Comment by GLUEHazard** [comment]
yes

**Comment by GLUEHazard** [comment]
idk if we could hop in a discord or something so i could screen share my issue so i can show you

**Comment by xJon** [comment]
@GLUEHazard Can you do `jstack -F <pid>`? That should force a thread dump.

**Comment by GLUEHazard** [comment]
Cannot connect to core dump or remote debug server. Use jhsdb jstack instead

**Comment by GLUEHazard** [comment]
so i can get a dump until the point the process gets suspended

**Comment by GLUEHazard** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/132792087/236700269-60672954-8e33-430f-aed1-ead464a30585.png)

**Comment by xJon** [comment]
Can you try `jhsdb jstack --pid`?

**Comment by GLUEHazard** [comment]
C:\WINDOWS\system32>jhsdb jstack --pid 2456
Attaching to process ID 2456, please wait...
java.lang.RuntimeException: Type "GrowableArrayBase", referenced in VMStructs::localHotSpotVMStructs in the remote VM, was not present in the remote VMStructs::localHotSpotVMTypes table (should have been caught in the debug build of that VM). Can not continue.
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotTypeDataBase.lookupOrFail(HotSpotTypeDataBase.java:596)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotTypeDataBase.lookupType(HotSpotTypeDataBase.java:120)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotTypeDataBase.lookupOrCreateClass(HotSpotTypeDataBase.java:631)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotTypeDataBase.createType(HotSpotTypeDataBase.java:744)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotTypeDataBase.readVMTypes(HotSpotTypeDataBase.java:195)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotTypeDataBase.<init>(HotSpotTypeDataBase.java:89)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.setupVM(HotSpotAgent.java:417)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:337)
        at jdk.hotspot.agent/sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:141)
        at jdk.hotspot.agent/sun.jvm.hotspot.tools.Tool.start(Tool.java:203)
        at jdk.hotspot.agent/sun.jvm.hotspot.tools.Tool.execute(Tool.java:134)
        at jdk.hotspot.agent/sun.jvm.hotspot.tools.JStack.runWithArgs(JStack.java:90)
        at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.runJSTACK(SALauncher.java:302)
        at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.main(SALauncher.java:500)

**Comment by xJon** [comment]
I believe this could mean in this case it requires JDK 8 to do this.
If you're willing to try to uninstall the current JDK and install https://adoptium.net/temurin/releases/?version=8 and try again, it might help.
I apologize for not being confident in my support here, this is a strange case that I have yet to encounter before.

**Comment by GLUEHazard** [comment]
same message

**Comment by GLUEHazard** [comment]
like I said idk if we could hop in a discord

**Comment by xJon** [comment]
> same message

Did you uninstall the previous JDK version?
 
Beyond that, I'm not sure how to help further right now. I'll see if someone else could help.

**Comment by GLUEHazard** [comment]
Error attaching to process: sun.jvm.hotspot.runtime.VMVersionMismatchException: Supported versions are 25.372-b07. Target VM is 25.371-b11
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.runtime.VMVersionMismatchException: Supported versions are 25.372-b07. Target VM is 25.371-b11

**Comment by xJon** [comment]
I believe this means there's a subversion mismatch between Java 8 371 (SE, running the server) and Java 8 372 (the JDK for the thread dump). Unfortunately I don't believe there is Java 8 SE 372. This seems to only affect when using `-F`, does it still hang without using `-F`?

**Comment by GLUEHazard** [comment]
yes

**Comment by GLUEHazard** [comment]
so it only hangs once the server crashes

**Comment by GLUEHazard** [comment]
C:\WINDOWS\system32>jstack 10180
2023-05-07 16:41:48
Full thread dump OpenJDK 64-Bit Server VM (25.372-b07 mixed mode):

"Downloader 0" #55 daemon prio=5 os_prio=0 tid=0x000002579d71b000 nid=0x4350 waiting on condition [0x000000840c4fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000045aadbb30> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

"pool-3-thread-3" #54 prio=5 os_prio=0 tid=0x000002579d725800 nid=0x2d90 waiting on condition [0x000000840c3ff000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000045aadbd78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

"pool-3-thread-2" #53 prio=5 os_prio=0 tid=0x000002579d724800 nid=0x4990 waiting on condition [0x000000840c1fe000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000045aadbd78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

"pool-3-thread-1" #52 prio=5 os_prio=0 tid=0x000002579d723800 nid=0x19ec waiting on condition [0x000000840bcfe000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000045aadbd78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

"Keep-Alive-SocketCleaner" #51 daemon prio=8 os_prio=1 tid=0x000002579d722000 nid=0x724 in Object.wait() [0x000000840bbff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000044a8cf750> (a sun.net.www.http.KeepAliveStreamCleaner)
        at sun.net.www.http.KeepAliveStreamCleaner.run(KeepAliveStreamCleaner.java:101)
        - locked <0x000000044a8cf750> (a sun.net.www.http.KeepAliveStreamCleaner)
        at java.lang.Thread.run(Thread.java:750)

"pool-2-thread-1" #50 prio=5 os_prio=0 tid=0x000002579d721800 nid=0x1ca8 waiting on condition [0x000000840c0ff000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000045aadc500> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

"Netty Server IO #0" #44 daemon prio=5 os_prio=0 tid=0x000002579d718000 nid=0x4724 runnable [0x000000840bdfe000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:314)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:293)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:174)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x000000045aadf870> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000045aadf888> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000045aadf7f0> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:750)

"LadyLib HTTP Helper" #41 prio=5 os_prio=0 tid=0x000002579d71e000 nid=0x7a0 waiting on condition [0x000000840baff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000045aadfad0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

"ForkJoinPool.commonPool-worker-2" #28 daemon prio=5 os_prio=0 tid=0x000002579ca7a000 nid=0x494c waiting on condition [0x000000840b9fe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004436a16d0> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

"ForkJoinPool.commonPool-worker-1" #27 daemon prio=5 os_prio=0 tid=0x000002579d5bc000 nid=0x2ff4 waiting on condition [0x000000840b8ff000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004436a16d0> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

"DestroyJavaVM" #26 prio=5 os_prio=0 tid=0x00000257dcd45800 nid=0xd18 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Server console handler" #25 daemon prio=5 os_prio=0 tid=0x00000257ff5c9800 nid=0x1bb8 runnable [0x000000840b7ff000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x000000044470e868> (a java.io.BufferedInputStream)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x0000000440006058> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        - locked <0x0000000440006058> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:105)

"Server thread" #23 prio=5 os_prio=0 tid=0x00000257fd915000 nid=0x34c8 runnable [0x000000840b6ff000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at drzhark.customspawner.configuration.CMSConfiguration.load(CMSConfiguration.java:296)
        at drzhark.customspawner.environment.EnvironmentSettings.populateSpawnBiomes(EnvironmentSettings.java:647)
        at drzhark.customspawner.environment.EnvironmentSettings.updateSettings(EnvironmentSettings.java:198)
        at drzhark.customspawner.utils.CMSUtils.addWorldEnvironment(CMSUtils.java:144)
        at drzhark.customspawner.EventHooks.onWorldLoad(EventHooks.java:171)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_851_EventHooks_onWorldLoad_Load.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
        at java.lang.Thread.run(Thread.java:750)

"Server Infinisleeper" #22 daemon prio=5 os_prio=0 tid=0x00000257ffbe5800 nid=0x1ad4 waiting on condition [0x000000840b5ff000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:82)

"Snooper Timer" #21 daemon prio=5 os_prio=0 tid=0x00000257fc041000 nid=0x1f18 in Object.wait() [0x000000840b4ff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000004409c1998> (a java.util.TaskQueue)
        at java.lang.Object.wait(Object.java:502)
        at java.util.TimerThread.mainLoop(Timer.java:526)
        - locked <0x00000004409c1998> (a java.util.TaskQueue)
        at java.util.TimerThread.run(Timer.java:505)

"Service Thread" #11 daemon prio=9 os_prio=0 tid=0x00000257fa179000 nid=0xb74 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #10 daemon prio=9 os_prio=2 tid=0x00000257fa147000 nid=0x1398 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #9 daemon prio=9 os_prio=2 tid=0x00000257fa139800 nid=0x1020 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #8 daemon prio=9 os_prio=2 tid=0x00000257fa137000 nid=0x27d0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 tid=0x00000257fa135000 nid=0x4938 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #6 daemon prio=5 os_prio=2 tid=0x00000257fa12f000 nid=0x1dd8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #5 daemon prio=9 os_prio=2 tid=0x00000257fa12a000 nid=0x30ac runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x00000257fa129800 nid=0x382c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000257fa0bc800 nid=0xe40 in Object.wait() [0x000000840aafe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000444af6ad0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x0000000444af6ad0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:188)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000257fa0b4000 nid=0x3a58 in Object.wait() [0x000000840a9ff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000444af6c88> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x0000000444af6c88> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=2 tid=0x00000257fa0b1800 nid=0x1c48 runnable

"Gang worker#0 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd5d800 nid=0x2704 runnable

"Gang worker#1 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd5f000 nid=0x1248 runnable

"Gang worker#2 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd61000 nid=0x26a8 runnable

"Gang worker#3 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd63000 nid=0x3b1c runnable

"Gang worker#4 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd65800 nid=0x4840 runnable

"Gang worker#5 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd67000 nid=0x11dc runnable

"Gang worker#6 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd6c000 nid=0xd28 runnable

"Gang worker#7 (Parallel GC Threads)" os_prio=2 tid=0x00000257dcd6d800 nid=0x32b4 runnable

"G1 Main Concurrent Mark GC Thread" os_prio=2 tid=0x00000257dce09000 nid=0x2e50 runnable

"Gang worker#0 (G1 Parallel Marking Threads)" os_prio=2 tid=0x00000257dce0a000 nid=0x2e4 runnable

"Gang worker#1 (G1 Parallel Marking Threads)" os_prio=2 tid=0x00000257dce0a800 nid=0x19e4 runnable

"G1 Concurrent Refinement Thread#0" os_prio=2 tid=0x00000257dcd8a800 nid=0x38c8 runnable

"G1 Concurrent Refinement Thread#1" os_prio=2 tid=0x00000257dcd86800 nid=0xa38 runnable

"G1 Concurrent Refinement Thread#2" os_prio=2 tid=0x00000257dcd85000 nid=0x23f0 runnable

"G1 Concurrent Refinement Thread#3" os_prio=2 tid=0x00000257dcd82000 nid=0x3e24 runnable

"G1 Concurrent Refinement Thread#4" os_prio=2 tid=0x00000257dcd81000 nid=0xe08 runnable

"G1 Concurrent Refinement Thread#5" os_prio=2 tid=0x00000257dcd7e000 nid=0x11d0 runnable

"G1 Concurrent Refinement Thread#6" os_prio=2 tid=0x00000257dcd79800 nid=0x49f4 runnable

"G1 Concurrent Refinement Thread#7" os_prio=2 tid=0x00000257dcd73000 nid=0x3584 runnable

"G1 Concurrent Refinement Thread#8" os_prio=2 tid=0x00000257dcd72000 nid=0x48d8 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x00000257fa17c800 nid=0x3c94 waiting on condition

JNI global references: 2964


C:\WINDOWS\system32>

**Comment by xJon** [comment]
I assume using `jcmd <pid> Thread.print` also wouldn't work, but perhaps you can try?

**Comment by GLUEHazard** [comment]
this is what i get before it freezes

**Comment by GLUEHazard** [comment]
C:\WINDOWS\system32>jcmd 10180 Thread.print
10180:
It hangs as well

**Comment by GLUEHazard** [comment]
this is the last thing my server says in the cmd
---------------------------------------------------------
[16:43:58] [Server thread/WARN] [minecraft/WorldServer]: Keeping entity mocreatures:ostrich that already exists with UUID 55ab8921-7d93-4ec2-8218-269ddd01d37e
[16:43:58] [Server thread/WARN] [minecraft/WorldServer]: Keeping entity mocreatures:fly that already exists with UUID b73a965c-edb5-4a0c-8862-125847345d71
[16:43:58] [Server thread/WARN] [minecraft/WorldServer]: Keeping entity mocreatures:goldfish that already exists with UUID c6924091-1fa2-45c0-b921-305114544a94
[16:43:58] [Server thread/WARN] [minecraft/WorldServer]: Keeping entity minecraft:llama that already exists with UUID decf1e4b-0d02-4537-98d1-f67f01a7db3c
[16:43:58] [Server thread/WARN] [minecraft/WorldServer]: Keeping entity mocreatures:fly that already exists with UUID f983c798-6211-4480-b058-1fada4d52617

**Comment by xJon** [comment]
You said that this issue happens with [Tekxit ](https://www.technicpack.net/modpack/tekxit-314-official-1122.1718228/mods)as well? I don't believe it has Mo' Creatures installed so I doubt that is the cause, although you could try manually removing it.

When the server hangs, can you try to in the server window to press the CTRL, SHIFT, and Pause keys together?

**Comment by GLUEHazard** [comment]
I pressed the CTRL, SHIFT, and Pause keys together and it did something but didnt fix it

**Comment by xJon** [comment]
In this case because there's no error in the log as the game freezes rather than crash, and we've unable to get a thread dump, and you mentioned this also happens with Tekxit but not with other modpacks not from Technic - the only suggestion I have is is for you to manually remove some mods to find which one/s cause the issue. You can also try to cross compare which mods are both in Hexxit II and Tekxit but not in other modpacks that didn't cause this issue for you.
You can try with Mo' Creatures and Custom Mob Spawner as you said they appeared last in the log, or other ones, I'm truly unsure as I'm not able to reproduce this issue.
Sorry for not having a better idea than that.

**Comment by xJon** [comment]
Closed due to inactivity (will reopen if requested).
Also worth trying out with the new update.
