### ISSUE TITLE
Cant start the server run.bat

### ISSUE THREAD

**Issue by SohPandaa** [xJon/Hexxit-II#207]
[Hexxit II] Server is starting...
[Hexxit II] Hopefully you're running Java 8!
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

I keep getting this error I have java 8 installed and everything run other minecraft servers just fine, any suggestions to fix?

**Comment by xJon** [comment]
In this case you must have Java 8 installed alongside other versions, and it is not detecting Java 8.
You can join Technic's Discord over https://discord.com/invite/technic and see this guide: https://discord.com/channels/42463947818795009/96563656271093760/903722624499200011
